### ISSUE TITLE
Help - dealing with multiple selection

### ISSUE THREAD

**Issue by iongion** [svgdotjs/svg.select.js#56]
How would you recommend when dealing with multiple selected objects ?

I like that the current implementation does not affect selected object structure, but for dealing with multiple selected objects , I dont see any other way than upon selection , adding the selected object to a group and then selectize on the group.

But this is:
- changing the document structure which is not desirable
- have unknown transform effects

What do you think ?

I would take this path as SVG.js is still very light compared to Konva or Fabric that include such methods, but It is hard to just use browser's inspect element that I so like when using SVG.js

**Comment by Fuzzyma** [comment]
That is a question I am dealing with since years!
I first hat this issue when I wrote the resize plugin. Upon resizing a shape, is it just changing the with and height (or coordinates) or is it a transformation (scale)? The same goes for selecting multiple elements. When you put them together in a group and move them around: should I move all objects in that group separately or just transform the whole group? I think programs like pfotoshop differentiate between those too. There is an explicit transformation mode while any other movement is done directly in coordinates.

Translates to your problem: it depends. For the sake of simplicity it might be easier to add a group, do whatever you need to do and call ungroup() when it's done. When you don't want changes in the object structure you would need to rewrite the plugin to allow multiple selections
